/** Writes api/openapi.yaml from the route schemas (no server started, no network). */
import { writeFileSync } from 'node:fs';
import path from 'node:path';
import { stringify } from 'yaml';
import { buildApp } from './app.js';
import { loadConfig } from './config.js';
import { openDatabase } from './db/client.js';

export async function generateOpenApi(): Promise<string> {
  const config = loadConfig({ NODE_ENV: 'test', ENCRYPTION_KEY: Buffer.alloc(32).toString('base64'), FRONTEND_DIST: '' });
  const database = await openDatabase({});
  const { app } = await buildApp(config, database, { logger: false });
  await app.ready();
  const doc = stringify(app.swagger(), { lineWidth: 0 });
  await app.close();
  await database.close();
  return `# Generated by \`npm run openapi\` from the Fastify route schemas. Do not edit by hand.\n${doc}`;
}

if (process.argv[1] && path.resolve(process.argv[1]) === path.resolve(import.meta.filename)) {
  const out = path.resolve(import.meta.dirname, '../../api/openapi.yaml');
  writeFileSync(out, await generateOpenApi());
  console.log(`Wrote ${out}`);
}
